// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAw2fYZGc3Ev7nbYyFwqp_pItu8NZzarE',
    appId: '1:249150255056:web:9e1c9e0591466fbdea13d5',
    messagingSenderId: '249150255056',
    projectId: 'loginauth-8e36c',
    authDomain: 'loginauth-8e36c.firebaseapp.com',
    storageBucket: 'loginauth-8e36c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNlQ58oMRehnMIqE5vG7S-hztxltw130A',
    appId: '1:249150255056:android:1a11365c526e8c02ea13d5',
    messagingSenderId: '249150255056',
    projectId: 'loginauth-8e36c',
    storageBucket: 'loginauth-8e36c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd4mvsRpmDR-wSFPpiuMj12m31kFM7Rl0',
    appId: '1:249150255056:ios:1a8ef9924805abe9ea13d5',
    messagingSenderId: '249150255056',
    projectId: 'loginauth-8e36c',
    storageBucket: 'loginauth-8e36c.appspot.com',
    iosBundleId: 'com.example.emailPasswordLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd4mvsRpmDR-wSFPpiuMj12m31kFM7Rl0',
    appId: '1:249150255056:ios:d5da5a73202406b1ea13d5',
    messagingSenderId: '249150255056',
    projectId: 'loginauth-8e36c',
    storageBucket: 'loginauth-8e36c.appspot.com',
    iosBundleId: 'com.example.emailPasswordLogin.RunnerTests',
  );
}
